/**
 * Merge a freshly-computed landing fixture (typically a short rolling window such
 * as the weekly 6-month run) into a previously published full-history fixture.
 *
 * Why this exists: the weekly pipeline rebuilds the published fixture from scratch
 * each run. The pre-1990s..present history is regenerated by CPI-chaining from a
 * recent observed "base" month. Once the rolling window moves entirely past the
 * trailing edge of the annual CPI dataset (which always lags ~1-2 years), no base
 * can be chosen, the CPI backfill silently yields nothing, and a from-scratch write
 * would overwrite decades of history with only the few processed months.
 *
 * Merging fresh months on top of the prior full history makes the publish step
 * additive and immune to that trailing-edge problem: recent months are refreshed,
 * historical months are preserved.
 */

import {
  buildCountryDiagnosticsFromRecords,
  type LandingFixtureCountryData,
  type LandingFixtureCountryRecord,
  type LandingFixturePayload,
} from './fixture-builder.js';

function latestRecordMonth(records: Readonly<Record<string, LandingFixtureCountryRecord>>): string {
  let max = '';
  for (const m of Object.keys(records)) {
    if (m > max) max = m;
  }
  return max;
}

function mergeCountry(
  previous: LandingFixtureCountryData | undefined,
  fresh: LandingFixtureCountryData | undefined,
): LandingFixtureCountryData {
  if (!previous && fresh) return fresh;
  if (previous && !fresh) return previous;
  if (!previous || !fresh) {
    throw new Error('mergeCountry called without any country payload');
  }

  const mergedRecords: Record<string, LandingFixtureCountryRecord> = {
    ...previous.records,
    ...fresh.records,
  };

  const useFreshSnapshot = latestRecordMonth(fresh.records) >= latestRecordMonth(previous.records);
  const base = useFreshSnapshot ? fresh : previous;

  return {
    name: base.name,
    currency: base.currency,
    region: base.region,
    basket_version: base.basket_version,
    alpha: base.alpha,
    market_type: base.market_type,
    diagnostics: buildCountryDiagnosticsFromRecords(mergedRecords),
    records: mergedRecords,
    latest_snapshot: base.latest_snapshot,
  };
}

/** Sorted union of every per-country record month (honest slider / chart axis). */
export function honestMonthsFromPayload(payload: LandingFixturePayload): string[] {
  const monthSet = new Set<string>();
  for (const code of Object.keys(payload.countries)) {
    const records = payload.countries[code]?.records;
    if (!records) continue;
    for (const m of Object.keys(records)) monthSet.add(m);
  }
  return [...monthSet].sort();
}

export function withHonestMonths(payload: LandingFixturePayload): LandingFixturePayload {
  return { ...payload, months: honestMonthsFromPayload(payload) };
}

/**
 * Produce an additive union of `previous` and `fresh`. `fresh` is authoritative for
 * its own months and for top-level methodology/schema/generated_at metadata.
 * `months` is the union of record keys, not an advertised empty range.
 */
export function mergeLandingFixturePayloads(
  previous: LandingFixturePayload,
  fresh: LandingFixturePayload,
): LandingFixturePayload {
  const codes = new Set<string>([
    ...Object.keys(previous.countries),
    ...Object.keys(fresh.countries),
  ]);

  const countries: Record<string, LandingFixtureCountryData> = {};
  for (const code of codes) {
    countries[code] = mergeCountry(previous.countries[code], fresh.countries[code]);
  }

  const merged: LandingFixturePayload = {
    schema_version: fresh.schema_version,
    methodology_version: fresh.methodology_version,
    generated_at: fresh.generated_at,
    months: [],
    countries,
  };
  return withHonestMonths(merged);
}

/** Total per-country monthly records across the whole payload (collapse-guard metric). */
export function countFixtureRecords(payload: LandingFixturePayload): number {
  let total = 0;
  for (const code of Object.keys(payload.countries)) {
    total += Object.keys(payload.countries[code]?.records ?? {}).length;
  }
  return total;
}

export function recordCountsPerCountry(payload: LandingFixturePayload): number[] {
  return Object.keys(payload.countries)
    .map((code) => Object.keys(payload.countries[code]?.records ?? {}).length)
    .sort((a, b) => a - b);
}

export function medianRecordsPerCountry(payload: LandingFixturePayload): number {
  const counts = recordCountsPerCountry(payload);
  if (counts.length === 0) return 0;
  const mid = Math.floor(counts.length / 2);
  if (counts.length % 2 === 1) return counts[mid] ?? 0;
  return ((counts[mid - 1] ?? 0) + (counts[mid] ?? 0)) / 2;
}

/** Median country-record count divided by advertised `payload.months.length`. */
export function fixtureDensityRatio(payload: LandingFixturePayload): number {
  if (payload.months.length === 0) return 1;
  return medianRecordsPerCountry(payload) / payload.months.length;
}

export const COLLAPSE_RATIO = 0.5;
export const DENSITY_MIN_MONTHS = 24;
export const DENSITY_RATIO = 0.5;

export function fixtureFailsDensityGuard(
  payload: LandingFixturePayload,
  opts?: { minMonths?: number; ratio?: number },
): boolean {
  const minMonths = opts?.minMonths ?? DENSITY_MIN_MONTHS;
  const ratio = opts?.ratio ?? DENSITY_RATIO;
  if (payload.months.length < minMonths) return false;
  return fixtureDensityRatio(payload) < ratio;
}
